---

version: "3"

services:
    cups:
        build: .
        container_name: Cups
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - "631:631"
        devices:
            - /dev/bus/usb:/dev/bus/usb
        environment:
            PRINTER1_ENABLE: 1
            PRINTER1_NAME: Dymo
            PRINTER1_DEVURI: usb://DYMO/LabelWriter%20450?serial=0101011234560
            PRINTER1_DRIVER: sample.drv/dymo.ppd
