name: Build

on: [push]

jobs:
  docker-build:
    name: Docker Build
    runs-on: PiLab
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
            docker build -t dymo-cups .