name: Static-Analysis

on: [push]

jobs:
    Shell-Lint_Check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Download Packages
              run: |
                sudo apt-get install shellcheck 

            - name: Shell Check
              run: |
                shellcheck *.sh

    Dockerfile_Lint_Check:
        name: Dockerfile Lint Check
        runs-on: ubuntu-latest
        steps:    
            - name: Checkout Code
              uses: actions/checkout@v2    

            - name: Download Packages
              run: |
                wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64 
                chmod +x /bin/hadolint .

            - name: Dockerfile Lint
              run: |
                hadolint --failure-threshold error --verbose *Dockerfile

            - name: Docker Compose Lint
              run: |
                docker-compose config --quiet || { echo "Invalid Docker Compose file"; exit 1; }

    Markdown_Lint_Check:
        name: Markdown Lint Check
        runs-on: ubuntu-latest
        steps:
            - name: Install markdownlint-cli
              run: npm install -g markdownlint-cli

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run markdownlint
              run: markdownlint '**/*.md'
                

            